### PR TITLE
Try latest TomEE version for release build

### PR DESCRIPTION
**Pull request by tandraschko**

### CODE REVIEW

**Review by fpapon — APPROVED** [review]

**Comment by rmannibucau** [comment]
TomEE 9.1 is jakarta 9.1 right? So javax API just relocated (means not jakarta API) so will be breaking when we'll move to v10.
Ultimately I'd prefer TomEE 10.0.0 with batchee shade then BatchEE 2.0.0 with TomEE 10 since there is no breaking API *from* these versions in the distro of both project whereas the opposite has breaking changes if I'm not wrong - at least in CDI land for BatchEE.

**Comment by rzo1** [comment]
Yes, TomEE 9.1 is EE9.1. BatchEE 2.0.0 targets EE10 and has the CDI 4 changes. 

But for TomEE 10 Milestone, we need BatchEE 🙃 so hen egg kind of thing.

**Comment by rzo1** [comment]
TomEE 9.1 uses the (reference) Jakarta API artifacts (no relocations) for EE 9.1

**Comment by rmannibucau** [comment]
ok so we aim at using v10 to avoid multiple breakages in the jakarta land as much as we can (we know 9 -> 10 will break cdi users for ex)

**Comment by tandraschko** [comment]
I dont understand the discussion? We need a non-snapshot dependency for the release, and its a chicken egg problem.
Does batchee shade something from TomEE?

**Comment by rmannibucau** [comment]
@tandraschko we deliver an openejb distro (for the old like me we don't care of tom(ee) part but only openejb to enable to run EE batches)

**Comment by tandraschko** [comment]
But its not a required or transitiv dependency? Not nice then but also no problem, right?
Or what exactly is the distro? A zip with both openejb and batchee jars?

**Comment by rmannibucau** [comment]
> But its not a required or transitiv dependency? Not nice then but also no problem, right?
> Or what exactly is the distro? A zip with both openejb and batchee jars?

Yep so it is required as a runtime dependency even if to not break pom consumers we use provided scope as a workaround.

**Pull request closed without merging**
